
import { Attraction, Restaurant, Hotel } from './types';

export const HOTELS: Hotel[] = [
  {
    id: 'gran-marquise',
    name: { en: 'Hotel Gran Marquise', pt: 'Hotel Gran Marquise', es: 'Hotel Gran Marquise', fr: 'Hôtel Gran Marquise' },
    category: 'Luxury',
    rating: 5.0,
    pricePerNight: 850,
    address: { en: '3980 Beira Mar Avenue, Mucuripe', pt: 'Av. Beira Mar, 3980, Mucuripe', es: 'Avenida Beira Mar, 3980, Mucuripe', fr: 'Avenue Beira Mar, 3980, Mucuripe' },
    description: {
      en: 'The most prestigious luxury hotel in Fortaleza, located in the elegant Mucuripe area with a stunning rooftop pool.',
      pt: 'O hotel de luxo mais prestigiado de Fortaleza, localizado na elegante área do Mucuripe, com uma piscina deslumbrante na cobertura.',
      es: 'El hotel de lujo más prestigioso de Fortaleza, ubicado en la elegante zona de Mucuripe con una impresionante piscina en la azotea.',
      fr: 'L\'hôtel de luxe le plus prestigieux de Fortaleza, situé dans le quartier élégant de Mucuripe avec une superbe piscine sur le toit.'
    },
    amenities: { en: ['Spa', 'Rooftop Pool', 'Fitness Center', 'Ocean View'], pt: ['Spa', 'Piscina na Cobertura', 'Academia', 'Vista Mar'], es: ['Spa', 'Piscina en la Azotea', 'Gimnasio', 'Vista al Mar'], fr: ['Spa', 'Piscine sur le toit', 'Salle de sport', 'Vue sur la mer'] },
    imageUrl: 'https://cf.bstatic.com/xdata/images/hotel/max1024x768/602301255.jpg?k=2bdd113d124105b61ac09fc6d431e7244d064bf804ca0b6f9ac4b8938895d0f8&o=',
    coords: { lat: -3.7275, lng: -38.4865 }
  },
  {
    id: 'luzeiros',
    name: { en: 'Hotel Luzeiros', pt: 'Hotel Luzeiros', es: 'Hotel Luzeiros', fr: 'Hôtel Luzeiros' },
    category: 'Luxury',
    rating: 4.8,
    pricePerNight: 620,
    address: { en: '2600 Beira Mar Avenue', pt: 'Av. Beira Mar, 2600', es: 'Avenida Beira Mar, 2600', fr: 'Avenue Beira Mar, 2600' },
    description: { en: 'A modern design hotel at Meireles Beach, offering sophisticated rooms and great city views.', pt: 'Um hotel de design moderno na Praia do Meireles, oferecendo quartos sofisticados e ótimas vistas da cidade.', es: 'Un hotel de diseño moderno en la playa de Meireles, con habitaciones sofisticadas y excelentes vistas de la ciudad.', fr: 'Un hôtel au design moderne sur la plage de Meireles, proposant des chambres sophistiquées et de superbes vues sur la ville.' },
    amenities: { en: ['Design', 'Pool', 'Fitness', 'WiFi'], pt: ['Design', 'Piscina', 'Academia', 'WiFi'], es: ['Diseño', 'Piscina', 'Gimnasio', 'WiFi'], fr: ['Design', 'Piscine', 'Fitness', 'WiFi'] },
    imageUrl: 'https://lirp.cdn-website.com/ba3b79d1/dms3rep/multi/opt/lh_sao_luis_ft-04-1-1920w.webp',
    coords: { lat: -3.7252, lng: -38.4958 }
  },
  {
    id: 'praiano',
    name: { en: 'Praiano Hotel', pt: 'Praiano Hotel', es: 'Praiano Hotel', fr: 'Hôtel Praiano' },
    category: 'Beachfront',
    rating: 4.5,
    pricePerNight: 410,
    address: { en: '2800 Beira Mar Avenue', pt: 'Av. Beira Mar, 2800', es: 'Avenida Beira Mar, 2800', fr: 'Avenue Beira Mar, 2800' },
    description: { en: 'Classic beachfront hotel at the heart of the Beira Mar promenade.', pt: 'Hotel clássico à beira-mar no coração do calçadão da Beira Mar.', es: 'Hotel clásico frente al mar en el corazón del paseo de Beira Mar.', fr: 'Hôtel classique en bord de mer au cœur de la promenade Beira Mar.' },
    amenities: { en: ['Ocean View', 'Pool', 'Restaurant'], pt: ['Vista Mar', 'Piscina', 'Restaurante'], es: ['Vista al Mar', 'Piscina', 'Restaurante'], fr: ['Vue mer', 'Piscine', 'Restaurant'] },
    imageUrl: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2a/e7/bd/aa/caption.jpg?w=900&h=500&s=1',
    coords: { lat: -3.7255, lng: -38.4942 }
  },
  {
    id: 'seara-praia',
    name: { en: 'Seara Praia Hotel', pt: 'Seara Praia Hotel', es: 'Seara Praia Hotel', fr: 'Hôtel Seara Praia' },
    category: 'Beachfront',
    rating: 4.6,
    pricePerNight: 450,
    address: { en: '3080 Beira Mar Avenue, Meireles', pt: 'Av. Beira Mar, 3080, Meireles', es: 'Avenida Beira Mar, 3080, Meireles', fr: 'Avenue Beira Mar, 3080, Meireles' },
    description: { en: 'Modern hotel offering high-quality service and a panoramic rooftop.', pt: 'Hotel moderno que oferece serviço de alta qualidade e cobertura panorâmica.', es: 'Hotel moderno que ofrece un servicio de alta calidad y una azotea panorámica.', fr: 'Hôtel moderne offrant un service de haute qualidade et un toit panoramique.' },
    amenities: { en: ['Pool', 'Sauna', 'Business Center'], pt: ['Piscina', 'Sauna', 'Centro de Negócios'], es: ['Piscina', 'Sauna', 'Centro de Negocios'], fr: ['Piscine', 'Sauna', 'Centre d\'affaires'] },
    imageUrl: 'https://seara-praia-hotel.hoteis-noreste-de-brasil.com/data/Imgs/OriginalPhoto/15767/1576708/1576708481/img-seara-praia-hotel-fortaleza-ceara-15.JPEG',
    coords: { lat: -3.7248, lng: -38.4955 }
  },
  {
    id: 'mareiro',
    name: { en: 'Mareiro Hotel', pt: 'Mareiro Hotel', es: 'Mareiro Hotel', fr: 'Hôtel Mareiro' },
    category: 'Beachfront',
    rating: 4.6,
    pricePerNight: 480,
    address: { en: '2380 Beira Mar Avenue', pt: 'Av. Beira Mar, 2380', es: 'Avenida Beira Mar, 2380', fr: 'Avenue Beira Mar, 2380' },
    description: { en: 'Excellent beachfront location with several pools.', pt: 'Excelente localização à beira-mar com várias piscinas.', es: 'Excelente ubicación frente al mar con varias piscinas.', fr: 'Excellent emplacement en bord de mer avec plusieurs piscines.' },
    amenities: { en: ['Pools', 'Spa', 'WiFi'], pt: ['Piscinas', 'Spa', 'WiFi'], es: ['Piscinas', 'Spa', 'WiFi'], fr: ['Piscines', 'Spa', 'WiFi'] },
    imageUrl: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2d/02/fb/16/caption.jpg?w=900&h=500&s=1',
    coords: { lat: -3.7250, lng: -38.4988 }
  },
  {
    id: 'sonata-iracema',
    name: { en: 'Hotel Sonata de Iracema', pt: 'Hotel Sonata de Iracema', es: 'Hotel Sonata de Iracema', fr: 'Hôtel Sonata de Iracema' },
    category: 'Beachfront',
    rating: 4.4,
    pricePerNight: 390,
    address: { en: '1030 Beira Mar Avenue', pt: 'Av. Beira Mar, 1030', es: 'Avenida Beira Mar, 1030', fr: 'Avenue Beira Mar, 1030' },
    description: { en: 'Historic vibe at Iracema Beach.', pt: 'Vibração histórica na Praia de Iracema.', es: 'Ambiente histórico en la playa de Iracema.', fr: 'Ambiance historique sur la plage d\'Iracema.' },
    amenities: { en: ['Culture', 'Pool', 'Breakfast'], pt: ['Cultura', 'Piscina', 'Café da Manhã'], es: ['Cultura', 'Piscina', 'Desayuno'], fr: ['Culture', 'Piscine', 'Petit-déjeuner'] },
    imageUrl: 'https://media.staticontent.com/media/pictures/ebb91579-4f74-477f-8a0a-c3e9da66faf8/412x210',
    coords: { lat: -3.7228, lng: -38.5132 }
  },
  {
    id: 'crocobeach-hotel',
    name: { en: 'Crocobeach Hotel', pt: 'Crocobeach Hotel', es: 'Crocobeach Hotel', fr: 'Crocobeach Hôtel' },
    category: 'Beachfront',
    rating: 4.7,
    pricePerNight: 350,
    address: { en: '3125 Clóvis Arrais Maia Avenue', pt: 'Av. Clóvis Arrais Maia, 3125', es: 'Avenida Clóvis Arrais Maia, 3125', fr: 'Avenue Clóvis Arrais Maia, 3125' },
    description: { en: 'Modern beachfront hotel at Praia do Futuro.', pt: 'Hotel moderno à beira-mar na Praia do Futuro.', es: 'Hotel moderno frente al mar en Praia do Futuro.', fr: 'Hôtel moderne en bord de mer à Praia do Futuro.' },
    amenities: { en: ['Beach Club', 'Pool', 'Gym'], pt: ['Clube de Praia', 'Piscina', 'Academia'], es: ['Club de Playa', 'Piscina', 'Gimnasio'], fr: ['Beach Club', 'Piscine', 'Salle de sport'] },
    imageUrl: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0c/5b/61/1f/crocobeach-hotel.jpg?w=900&h=500&s=1',
    coords: { lat: -3.7383, lng: -38.4552 }
  },
  {
    id: 'blue-tree',
    name: { en: 'Blue Tree Towers Fortaleza', pt: 'Blue Tree Towers Fortaleza', es: 'Blue Tree Towers Fortaleza', fr: 'Blue Tree Towers Fortaleza' },
    category: 'Business',
    rating: 4.3,
    pricePerNight: 350,
    address: { en: '2343 Beira Mar Avenue', pt: 'Av. Beira Mar, 2343', es: 'Avenida Beira Mar, 2343', fr: 'Avenue Beira Mar, 2343' },
    description: { en: 'Modern flat-style hotel.', pt: 'Hotel moderno estilo flat.', es: 'Moderno hotel estilo apartamento.', fr: 'Hôtel moderne de style appartement.' },
    amenities: { en: ['Kitchenette', 'Gym', 'Business'], pt: ['Copa', 'Academia', 'Negócios'], es: ['Cocina', 'Gimnasio', 'Negocios'], fr: ['Kitchenette', 'Salle de sport', 'Affaires'] },
    imageUrl: 'https://cf.bstatic.com/xdata/images/hotel/max1024x768/477172864.jpg?k=82f6adebd4c091d18ccfed853d38ea94fd2473afbc27bc47d9e3bac9451f9dec&o=',
    coords: { lat: -3.7248, lng: -38.5002 }
  },
  {
    id: 'vila-gale',
    name: { en: 'Vila Galé Fortaleza', pt: 'Vila Galé Fortaleza', es: 'Vila Galé Fortaleza', fr: 'Vila Galé Fortaleza' },
    category: 'Luxury',
    rating: 4.7,
    pricePerNight: 550,
    address: { en: '3430 Dioguinho Avenue', pt: 'Av. Dioguinho, 3430', es: 'Avenida Dioguinho, 3430', fr: 'Avenue Dioguinho, 3430' },
    description: { en: 'A massive beachfront resort with exotic decor.', pt: 'Um resort enorme à beira-mar com decoração exótica.', es: 'Un enorme complejo frente al mar con decoración exótica.', fr: 'Un immense complexe en bord de mer avec un décor exotique.' },
    amenities: { en: ['Resort', 'Spa', 'Pools'], pt: ['Resort', 'Spa', 'Piscinas'], es: ['Resort', 'Spa', 'Piscinas'], fr: ['Resort', 'Spa', 'Piscines'] },
    imageUrl: 'https://d2h50f2ee3zau3.cloudfront.net/app/uploads/2026/03/11161922/vg_thumbnails_video-fortaleza.jpg',
    coords: { lat: -3.7402, lng: -38.4528 }
  },
  {
    id: 'carmel-magna',
    name: { en: 'Carmel Magna Praia Hotel', pt: 'Carmel Magna Praia Hotel', es: 'Carmel Magna Praia Hotel', fr: 'Carmel Magna Praia Hotel' },
    category: 'Luxury',
    rating: 4.6,
    pricePerNight: 580,
    address: { en: '1001 Iracema Avenue', pt: 'Av. Iracema, 1001', es: 'Avenida Iracema, 1001', fr: 'Avenue Iracema, 1001' },
    description: { en: 'Panoramic views of the Iracema coast.', pt: 'Vistas panorâmicas da costa de Iracema.', es: 'Vistas panorámicas de la costa de Iracema.', fr: 'Vue panoramique sur la côte d\'Iracema.' },
    amenities: { en: ['Modern', 'Pool', 'View'], pt: ['Moderno', 'Piscina', 'Vista'], es: ['Moderno', 'Piscina', 'Vista'], fr: ['Moderne', 'Piscine', 'Vue'] },
    imageUrl: 'https://magnapraiahotel.com.br/wp-content/themes/magna/assets/img/gal2.jpg',
    coords: { lat: -3.7225, lng: -38.5142 }
  },
  {
    id: 'ibis-iracema',
    name: { en: 'Ibis Fortaleza Praia de Iracema', pt: 'Ibis Fortaleza Praia de Iracema', es: 'Ibis Fortaleza Praia de Iracema', fr: 'Ibis Fortaleza Praia de Iracema' },
    category: 'Budget',
    rating: 4.1,
    pricePerNight: 240,
    address: { en: '800 Historiador Raimundo Girão Avenue', pt: 'Av. Hist. Raimundo Girão, 800', es: 'Avenida Hist. Raimundo Girão, 800', fr: 'Avenue Hist. Raimundo Girão, 800' },
    description: { en: 'Consistent quality and great value.', pt: 'Qualidade consistente e ótimo custo-benefício.', es: 'Calidad constante y excelente relação qualidade-precio.', fr: 'Qualité constante et excellent rapport qualité-prix.' },
    amenities: { en: ['WiFi', 'Bar', 'AC'], pt: ['WiFi', 'Bar', 'Ar Cond.'], es: ['WiFi', 'Bar', 'Aire Acond.'], fr: ['WiFi', 'Bar', 'Clim.'] },
    imageUrl: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/25/7a/b3/0f/fachada-pela-rua-monsenhor.jpg?w=900&h=-1&s=1',
    coords: { lat: -3.7222, lng: -38.5158 }
  },
  {
    id: 'ibis-styles',
    name: { en: 'Ibis Styles Fortaleza', pt: 'Ibis Styles Fortaleza', es: 'Ibis Styles Fortaleza', fr: 'Ibis Styles Fortaleza' },
    category: 'Budget',
    rating: 4.2,
    pricePerNight: 230,
    address: { en: '100 Senador Machado Street', pt: 'Rua Sen. Machado, 100', es: 'Calle Sen. Machado, 100', fr: 'Rue Sen. Machado, 100' },
    description: { en: 'Colorful and creatively designed.', pt: 'Colorido e com design criativo.', es: 'Colorido y de diseño creativo.', fr: 'Coloré au design créatif.' },
    amenities: { en: ['Design', 'WiFi'], pt: ['Design', 'WiFi'], es: ['Diseño', 'WiFi'], fr: ['Design', 'WiFi'] },
    imageUrl: 'https://www.ahstatic.com/photos/c2z2_ho_03_p_1024x768.jpg',
    coords: { lat: -3.7242, lng: -38.5082 }
  },
  {
    id: 'brasil-tropical',
    name: { en: 'Hotel Brasil Tropical', pt: 'Hotel Brasil Tropical', es: 'Hotel Brasil Tropical', fr: 'Hotel Brasil Tropical' },
    category: 'Beachfront',
    rating: 4.3,
    pricePerNight: 360,
    address: { en: '2323 Beira Mar Avenue', pt: 'Av. Beira Mar, 2323', es: 'Avenida Beira Mar, 2323', fr: 'Avenue Beira Mar, 2323' },
    description: { en: 'Comfortable apartments with kitchen.', pt: 'Apartamentos confortáveis com cozinha.', es: 'Apartamentos confortables con cocina.', fr: 'Appartements confortáveis avec cuisine.' },
    amenities: { en: ['Kitchen', 'View', 'Pool'], pt: ['Cozinha', 'Vista', 'Piscina'], es: ['Cocina', 'Vista', 'Piscina'], fr: ['Cuisine', 'Vue', 'Piscine'] },
    imageUrl: 'https://media.staticontent.com/media/pictures/7bfda5d6-1baf-4f45-ad1d-b250472a3d8e/412x210',
    coords: { lat: -3.7245, lng: -38.5015 }
  },
  {
    id: 'golden-fortaleza',
    name: { en: 'Golden Fortaleza by Intercity', pt: 'Golden Fortaleza by Intercity', es: 'Golden Fortaleza by Intercity', fr: 'Golden Fortaleza by Intercity' },
    category: 'Business',
    rating: 4.4,
    pricePerNight: 390,
    address: { en: '4260 Beira Mar Avenue', pt: 'Av. Beira Mar, 4260', es: 'Avenida Beira Mar, 4260', fr: 'Avenue Beira Mar, 4260' },
    description: { en: 'Prime location for business and leisure.', pt: 'Localização privilegiada para negócios e lazer.', es: 'Ubicación privilegiada para negocios y ocio.', fr: 'Emplacement privilégié pour les affaires et les loisirs.' },
    amenities: { en: ['Pool', 'Sauna', 'Business'], pt: ['Piscina', 'Sauna', 'Negócios'], es: ['Piscina', 'Sauna', 'Negocios'], fr: ['Piscine', 'Sauna', 'Affaires'] },
    imageUrl: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0b/a2/c6/17/intercity-golden-fortaleza.jpg?w=900&h=500&s=1',
    coords: { lat: -3.7282, lng: -38.4828 }
  },
  {
    id: 'stop-way-fortaleza',
    name: { en: 'Stop Way Hotel Fortaleza', pt: 'Stop Way Hotel Fortaleza', es: 'Stop Way Hotel Fortaleza', fr: 'Stop Way Hotel Fortaleza' },
    category: 'Budget',
    rating: 4.2,
    pricePerNight: 210,
    address: { en: '1500 Monsenhor Tabosa Avenue', pt: 'Av. Monsenhor Tabosa, 1500', es: 'Avenida Monsenhor Tabosa, 1500', fr: 'Avenue Monsenhor Tabosa, 1500' },
    description: { en: 'Practical and affordable near Praia de Iracema.', pt: 'Prático e acessível perto da Praia de Iracema.', es: 'Práctico y asequible cerca de Iracema.', fr: 'Pratique et abordable près d\'Iracema.' },
    amenities: { en: ['WiFi', 'AC', 'Breakfast'], pt: ['WiFi', 'Ar Cond.', 'Café'], es: ['WiFi', 'Aire', 'Desayuno'], fr: ['WiFi', 'Clim', 'Petit-D'] },
    imageUrl: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2a/36/60/e9/fachada.jpg?w=900&h=500&s=1',
    coords: { lat: -3.7235, lng: -38.5115 }
  }
];

export const RESTAURANTS: Restaurant[] = [
  {
    id: 'coco-bambu-beiramar',
    name: { en: 'Coco Bambu Beira Mar', pt: 'Coco Bambu Beira Mar', es: 'Coco Bambu Beira Mar', fr: 'Coco Bambu Beira Mar' },
    cuisine: { en: 'Seafood', pt: 'Frutos do Mar', es: 'Mariscos', fr: 'Fruits de mer' },
    category: 'Seafood',
    rating: 4.8,
    address: { en: '3698 Beira Mar Avenue', pt: 'Av. Beira Mar, 3698', es: 'Avenida Beira Mar, 3698', fr: 'Avenue Beira Mar, 3698' },
    openingHours: { en: '11:30 AM - 12:00 AM', pt: '11:30 - 00:00', es: '11:30 - 00:00', fr: '11:30 - 00:00' },
    priceRange: '$$$',
    description: { en: 'Iconic seafood at Beira Mar.', pt: 'Frutos do mar icônicos na Beira Mar.', es: 'Mariscos icónicos en Beira Mar.', fr: 'Fruits de mer emblématiques à Beira Mar.' },
    imageUrl: 'https://cocobambu.com.br/web/image/1201-bb2a5ab2/dsc_0466-2-dsc_0466.webp',
    coords: { lat: -3.7258, lng: -38.4905 }
  },
  {
    id: 'vignoli',
    name: { en: 'Vignoli', pt: 'Vignoli', es: 'Vignoli', fr: 'Vignoli' },
    cuisine: { en: 'Italian & Pizza', pt: 'Italiana e Pizza', es: 'Italiana y Pizza', fr: 'Italien et Pizza' },
    category: 'Italian',
    rating: 4.7,
    address: { en: '600 Virgílio Távora Avenue', pt: 'Av. Virgílio Távora, 600', es: 'Avenida Virgílio Távora, 600', fr: 'Avenue Virgílio Távora, 600' },
    openingHours: { en: '06:00 PM - 11:30 PM', pt: '18:00 - 23:30', es: '18:00 - 23:30', fr: '18:00 - 23:30' },
    priceRange: '$$',
    description: { en: 'Ultra-thin crispy pizza.', pt: 'Pizza crocante ultrafina.', es: 'Pizza crujiente ultrafina.', fr: 'Pizza croustillante ultra-fine.' },
    imageUrl: 'https://www.primeiramesa.com.br/storage//gallery_20680929d1634d4c24122d5fe9af53cc.jpeg',
    coords: { lat: -3.7352, lng: -38.4922 }
  },
  {
    id: 'cabana-primo',
    name: { en: 'Cabaña del Primo', pt: 'Cabaña del Primo', es: 'Cabaña del Primo', fr: 'Cabaña del Primo' },
    cuisine: { en: 'Steakhouse', pt: 'Churrascaria', es: 'Parrilla', fr: 'Steakhouse' },
    category: 'Fine Dining',
    rating: 4.9,
    address: { en: '1011 Maria Tomásia Street', pt: 'Rua Maria Tomásia, 1011', es: 'Calle Maria Tomásia, 1011', fr: 'Rue Maria Tomásia, 1011' },
    openingHours: { en: '12:00 PM - 11:00 PM', pt: '12:00 - 23:00', es: '12:00 - 23:00', fr: '12:00 - 23:00' },
    priceRange: '$$$$',
    description: { en: 'Argentinian steakhouse.', pt: 'Churrascaria argentina.', es: 'Parrilla argentina.', fr: 'Steakhouse argentin.' },
    imageUrl: 'https://cabanadelprimo.com.br/wp-content/uploads/2024/02/Foto-Fachada-Cabana.jpg',
    coords: { lat: -3.7388, lng: -38.4915 }
  },
  {
    id: 'geppos',
    name: { en: 'Geppos Restaurante', pt: 'Geppos Restaurante', es: 'Geppos Restaurante', fr: 'Restaurant Geppos' },
    cuisine: { en: 'Italian & Seafood', pt: 'Italiana e Frutos do Mar', es: 'Italiana y Mariscos', fr: 'Italien et Fruits de mer' },
    category: 'Fine Dining',
    rating: 4.6,
    address: { en: 'Jardim Open Mall, Meireles', pt: 'Jardim Open Mall, Meireles', es: 'Jardim Open Mall, Meireles', fr: 'Jardim Open Mall, Meireles' },
    openingHours: { en: '11:30 AM - 11:30 PM', pt: '11:30 - 23:30', es: '11:30 - 23:30', fr: '11:30 - 23:30' },
    priceRange: '$$$',
    description: { en: 'Elegant dining at Meireles.', pt: 'Jantar elegante no Meireles.', es: 'Cena elegante en Meireles.', fr: 'Dîner élégant à Meireles.' },
    imageUrl: 'https://www.grupogeppos.com.br/assets/img/geppos/restaurante.jpg',
    coords: { lat: -3.7312, lng: -38.4962 }
  },
  {
    id: 'colher-pau',
    name: { en: 'Colher de Pau', pt: 'Colher de Pau', es: 'Colher de Pau', fr: 'Colher de Pau' },
    cuisine: { en: 'Regional Brazilian', pt: 'Regional Brasileira', es: 'Regional Brasileña', fr: 'Régional Brésilien' },
    category: 'Brazilian Food',
    rating: 4.5,
    address: { en: '112 Ana Bilhar Street', pt: 'Rua Ana Bilhar, 112', es: 'Calle Ana Bilhar, 112', fr: 'Rue Ana Bilhar, 112' },
    openingHours: { en: '11:00 AM - 11:00 PM', pt: '11:00 - 23:00', es: '11:00 - 23:00', fr: '11:00 - 23:00' },
    priceRange: '$$',
    description: { en: 'Traditional Ceará food.', pt: 'Comida tradicional do Ceará.', es: 'Comida tradicional de Ceará.', fr: 'Cuisine traditionnelle du Ceará.' },
    imageUrl: 'https://viagemeturismo.abril.com.br/wp-content/uploads/2016/10/colher-pau-resto-jarbas-oliv.jpg',
    coords: { lat: -3.7298, lng: -38.4952 }
  },
  {
    id: 'ryori',
    name: { en: 'Ryori', pt: 'Ryori', es: 'Ryori', fr: 'Ryori' },
    cuisine: { en: 'Japanese', pt: 'Japonesa', es: 'Japonesa', fr: 'Japonais' },
    category: 'Fine Dining',
    rating: 4.8,
    address: { en: 'Shopping Buganvília, Meireles', pt: 'Shopping Buganvília, Meireles', es: 'Shopping Buganvília, Meireles', fr: 'Shopping Buganvília, Meireles' },
    openingHours: { en: '12:00 PM - 11:30 PM', pt: '12:00 - 23:30', es: '12:00 - 23:30', fr: '12:00 - 23:30' },
    priceRange: '$$$$',
    description: { en: 'Sophisticated Japanese cuisine.', pt: 'Culinária japonesa sofisticada.', es: 'Cocina japonesa sofisticada.', fr: 'Cuisine japonaise sophistiquée.' },
    imageUrl: 'https://media-cdn.tripadvisor.com/media/photo-s/16/1b/50/37/restaurante-ryori-iguatemi.jpg',
    coords: { lat: -3.7342, lng: -38.4982 }
  },
  {
    id: 'moleskine',
    name: { en: 'Moleskine Gastrobar', pt: 'Moleskine Gastrobar', es: 'Moleskine Gastrobar', fr: 'Moleskine Gastrobar' },
    cuisine: { en: 'Contemporary & Bar', pt: 'Contemporânea e Bar', es: 'Contemporânea e Bar', fr: 'Contemporain et Bar' },
    category: 'Nightlife',
    rating: 4.7,
    address: { en: '542 Professor Dias da Rocha Street', pt: 'Rua Prof. Dias da Rocha, 542', es: 'Calle Prof. Dias da Rocha, 542', fr: 'Rue Prof. Dias da Rocha, 542' },
    openingHours: { en: '05:00 PM - 01:00 AM', pt: '17:00 - 01:00', es: '17:00 - 01:00', fr: '17:00 - 01:00' },
    priceRange: '$$$',
    description: { en: 'Vibrant gastrobar.', pt: 'Gastrobar vibrante.', es: 'Gastrobar vibrante.', fr: 'Gastrobar animé.' },
    imageUrl: 'https://media-cdn.tripadvisor.com/media/photo-s/13/d5/65/e8/moleskine-gastrobar.jpg',
    coords: { lat: -3.7362, lng: -38.4932 }
  },
  {
    id: 'santa-grelha',
    name: { en: 'Santa Grelha', pt: 'Santa Grelha', es: 'Santa Grelha', fr: 'Santa Grelha' },
    cuisine: { en: 'Premium Steakhouse', pt: 'Churrascaria Premium', es: 'Parrilla Premium', fr: 'Steakhouse Premium' },
    category: 'Fine Dining',
    rating: 4.9,
    address: { en: '1130 Tibúrcio Cavalcante Street', pt: 'Rua Tibúrcio Cavalcante, 1130', es: 'Calle Tibúrcio Cavalcante, 1130', fr: 'Rue Tibúrcio Cavalcante, 1130' },
    openingHours: { en: '12:00 PM - 11:30 PM', pt: '12:00 - 23:30', es: '12:00 - 23:30', fr: '12:00 - 23:30' },
    priceRange: '$$$$',
    description: { en: 'High-end grill house.', pt: 'Casa de grelhados de luxo.', es: 'Parrilla de lujo.', fr: 'Grill house haut de gamme.' },
    imageUrl: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/29/86/cd/ae/santa-grelha-meireles.jpg?w=900&h=500&s=1',
    coords: { lat: -3.7382, lng: -38.5012 }
  },
  {
    id: 'cantinho-frango',
    name: { en: 'Cantinho do Frango', pt: 'Cantinho do Frango', es: 'Cantinho do Frango', fr: 'Cantinho do Frango' },
    cuisine: { en: 'Regional & Barbecue', pt: 'Regional e Grelhados', es: 'Regional y Parrilla', fr: 'Régional et Barbecue' },
    category: 'Brazilian Food',
    rating: 4.8,
    address: { en: '1335 Torres Câmara Street', pt: 'Rua Torres Câmara, 1335', es: 'Calle Torres Câmara, 1335', fr: 'Rue Torres Câmara, 1335' },
    openingHours: { en: '10:00 AM - 10:00 PM', pt: '10:00 - 22:00', es: '10:00 - 22:00', fr: '10:00 - 22:00' },
    priceRange: '$$',
    description: { en: 'Roasted chicken and beer.', pt: 'Frango assado e cerveja.', es: 'Pollo asado y cerveza.', fr: 'Poulet rôti et bière.' },
    imageUrl: 'https://cantinhodofrangooficial.com.br/wp-content/uploads/2022/11/Foto-4-1.png',
    coords: { lat: -3.7358, lng: -38.5088 }
  },
  {
    id: 'picanha-cowboy',
    name: { en: 'Picanha do Cowboy', pt: 'Picanha do Cowboy', es: 'Picanha do Cowboy', fr: 'Picanha do Cowboy' },
    cuisine: { en: 'Steakhouse', pt: 'Churrascaria', es: 'Parrilla', fr: 'Steakhouse' },
    category: 'Brazilian Food',
    rating: 4.5,
    address: { en: 'Dom Luís Avenue, 665', pt: 'Av. Dom Luís, 665', es: 'Avenida Dom Luís, 665', fr: 'Avenue Dom Luís, 665' },
    openingHours: { en: '11:00 AM - 12:00 AM', pt: '11:00 - 00:00', es: '11:00 - 00:00', fr: '11:00 - 00:00' },
    priceRange: '$$',
    description: { en: 'Classic picanha destination.', pt: 'Destino clássico para picanha.', es: 'Destino clásico de picanha.', fr: 'Destination classique para la picanha.' },
    imageUrl: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/07/e3/24/ea/picanha-do-cowboy-riomar.jpg?w=900&h=500&s=1',
    coords: { lat: -3.7332, lng: -38.4902 }
  },
  {
    id: 'la-bella-italia',
    name: { en: 'La Bella Italia', pt: 'La Bella Italia', es: 'La Bella Italia', fr: 'La Bella Italia' },
    cuisine: { en: 'Authentic Italian', pt: 'Italiana Autêntica', es: 'Italiana Auténtica', fr: 'Italien Authentique' },
    category: 'Italian',
    rating: 4.7,
    address: { en: '1000 Almirante Barroso Avenue', pt: 'Av. Alm. Barroso, 1000', es: 'Avenida Alm. Barroso, 1000', fr: 'Avenue Alm. Barroso, 1000' },
    openingHours: { en: '06:30 PM - 11:30 PM', pt: '18:30 - 23:30', es: '18:30 - 23:30', fr: '18:30 - 23:30' },
    priceRange: '$$$',
    description: { en: 'True Italian flavors.', pt: 'Sabores italianos verdadeiros.', es: 'Verdaderos sabores italianos.', fr: 'De vraies saveurs italiennes.' },
    imageUrl: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/13/0a/1a/1f/salao-climatizado.jpg?w=900&h=-1&s=1',
    coords: { lat: -3.7225, lng: -38.5122 }
  },
  {
    id: 'balcone-resto',
    name: { en: 'Balcone Restô', pt: 'Balcone Restô', es: 'Balcone Restô', fr: 'Balcone Restô' },
    cuisine: { en: 'Contemporary Italian', pt: 'Italiana Contemporânea', es: 'Italiana Contemporânea', fr: 'Italien Contemporain' },
    category: 'Italian',
    rating: 4.6,
    address: { en: '1000 Historiador Raimundo Girão Avenue', pt: 'Av. Hist. Raimundo Girão, 1000', es: 'Avenida Hist. Raimundo Girão, 1000', fr: 'Avenue Hist. Raimundo Girão, 1000' },
    openingHours: { en: '06:00 PM - 11:00 PM', pt: '18:00 - 23:00', es: '18:00 - 23:00', fr: '18:00 - 23:00' },
    priceRange: '$$',
    description: { en: 'Modern Italian dishes.', pt: 'Pratos italianos modernos.', es: 'Platos italianos modernos.', fr: 'Plats italiens modernes.' },
    imageUrl: 'https://casabalcone.com.br/wp-content/uploads/2021/03/restaurante-balcone-exterior-1599x940.jpg',
    coords: { lat: -3.7228, lng: -38.5108 }
  },
  {
    id: 'varanda-tropical',
    name: { en: 'Varanda Tropical', pt: 'Varanda Tropical', es: 'Varanda Tropical', fr: 'Varanda Tropical' },
    cuisine: { en: 'Regional & Seafood', pt: 'Regional e Frutos do Mar', es: 'Regional y Mariscos', fr: 'Régional et Fruits de mer' },
    category: 'Beach Restaurants',
    rating: 4.4,
    address: { en: 'Beira Mar Avenue, 2300', pt: 'Av. Beira Mar, 2300', es: 'Avenida Beira Mar, 2300', fr: 'Avenue Beira Mar, 2300' },
    openingHours: { en: '11:00 AM - 11:00 PM', pt: '11:00 - 23:00', es: '11:00 - 23:00', fr: '11:00 - 23:00' },
    priceRange: '$$',
    description: { en: 'Casual ocean-view dining.', pt: 'Jantar casual com vista mar.', es: 'Cena informal con vistas al mar.', fr: 'Dîner décontracté vue mer.' },
    imageUrl: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/11/de/17/e4/minha-tomada-fotografica.jpg?w=900&h=500&s=1',
    coords: { lat: -3.7248, lng: -38.5008 }
  },
  {
    id: 'parrileiro',
    name: { en: 'Parrileiro', pt: 'Parrileiro', es: 'Parrileiro', fr: 'Parrileiro' },
    cuisine: { en: 'Uruguayan Grill', pt: 'Grelhados Uruguaios', es: 'Parrilla Uruguaya', fr: 'Grill Uruguayen' },
    category: 'Fine Dining',
    rating: 4.7,
    address: { en: 'Dom Luís Avenue, 1100', pt: 'Av. Dom Luís, 1100', es: 'Avenida Dom Luís, 1100', fr: 'Avenue Dom Luís, 1100' },
    openingHours: { en: '12:00 PM - 11:00 PM', pt: '12:00 - 23:00', es: '12:00 - 23:00', fr: '12:00 - 23:00' },
    priceRange: '$$$',
    description: { en: 'Authentic South American grilling.', pt: 'Grelhados sul-americanos autênticos.', es: 'Parrilla sudamericana auténtica.', fr: 'Grillades sud-américaines authentiques.' },
    imageUrl: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2e/6c/01/ee/a-melhor-casa-de-carnes.jpg?w=900&h=500&s=1',
    coords: { lat: -3.7348, lng: -38.4892 }
  }
];

export const ATTRACTIONS: Attraction[] = [
  {
    id: 'iracema',
    title: { en: 'Iracema Beach', pt: 'Praia de Iracema', es: 'Playa de Iracema', fr: 'Plage d\'Iracema' },
    description: { en: 'Iconic beach known for its bohemian spirit and sunset views.', pt: 'Praia icônica conhecida por seu espírito boêmio e vista do pôr do sol.', es: 'Playa icónica conocida por su espíritu bohemio y vistas al atardecer.', fr: 'Plage emblématique connue pour son esprit bohème et ses vues sur le coucher du soleil.' },
    address: { en: 'Iracema Beach, Fortaleza - CE', pt: 'Praia de Iracema, Fortaleza - CE', es: 'Playa de Iracema, Fortaleza - CE', fr: 'Plage d\'Iracema, Fortaleza - CE' },
    openingHours: { en: 'Open 24h', pt: 'Aberto 24h', es: 'Abierto 24h', fr: 'Ouvert 24h' },
    rating: 4.7,
    category: 'Beaches',
    imageUrl: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/13/99/b0/42/beira-mar-avenue-fortaleza.jpg?w=700&h=400&s=1',
    coords: { lat: -3.7208, lng: -38.5173 },
    nearbyRestaurantIds: ['la-bella-italia', 'balcone-resto']
  },
  {
    id: 'porto-dunas',
    title: { en: 'Porto das Dunas', pt: 'Porto das Dunas', es: 'Porto das Dunas', fr: 'Porto das Dunas' },
    description: { en: 'Home to Beach Park, featuring high dunes and crystal clear waters.', pt: 'Lar do Beach Park, com dunas altas e águas cristalinas.', es: 'Hogar de Beach Park, con dunas altas y aguas cristalinas.', fr: 'Siège du Beach Park, avec de hautes dunes et des eaux cristallines.' },
    address: { en: 'Aquiraz, Metropolitan Area', pt: 'Aquiraz, Região Metropolitana', es: 'Aquiraz, Área Metropolitana', fr: 'Aquiraz, Zone métropolitaine' },
    openingHours: { en: 'Open 24h', pt: 'Aberto 24h', es: 'Abierto 24h', fr: 'Ouvert 24h' },
    rating: 4.9,
    category: 'Beaches',
    imageUrl: 'https://villaaquiraz.com.br/wp-content/uploads/2020/09/aquiraz_porto_das_dunas2.jpg',
    coords: { lat: -3.8392, lng: -38.3912 },
    nearbyRestaurantIds: []
  },
  {
    id: 'meireles',
    title: { en: 'Meireles Beach', pt: 'Praia do Meireles', es: 'Playa de Meireles', fr: 'Plage de Meireles' },
    description: { en: 'The most developed tourist area, famous for its craft market.', pt: 'A área turística mais desenvolvida, famosa por sua feirinha de artesanato.', es: 'La zona turística más desarrollada, famosa por su mercado artesanal.', fr: 'Le quartier touristique le plus développé, célèbre pour son mercado artisanal.' },
    address: { en: 'Beira Mar Avenue, Meireles', pt: 'Av. Beira Mar, Meireles', es: 'Avenida Beira Mar, Meireles', fr: 'Avenue Beira Mar, Meireles' },
    openingHours: { en: 'Open 24h', pt: 'Aberto 24h', es: 'Abierto 24h', fr: 'Ouvert 24h' },
    rating: 4.8,
    category: 'Beaches',
    imageUrl: 'https://img2.oastatic.com/img2/62458663/max/variant.webp',
    coords: { lat: -3.7252, lng: -38.4982 },
    nearbyRestaurantIds: ['geppos', 'ryori', 'colher-pau']
  },
  {
    id: 'mucuripe',
    title: { en: 'Mucuripe Beach', pt: 'Praia do Mucuripe', es: 'Playa de Mucuripe', fr: 'Plage de Mucuripe' },
    description: { en: 'Famous for its traditional jangada boats and the fresh fish market.', pt: 'Famosa pelas suas jangadas tradicionais e pelo mercado de peixes frescos.', es: 'Famosa por sus tradicionales jangadas y su mercado de pescado fresco.', fr: 'Célèbre pour ses jangadas traditionnelles et son marché aux poissons frais.' },
    address: { en: 'Beira Mar Avenue, Mucuripe', pt: 'Av. Beira Mar, Mucuripe', es: 'Avenida Beira Mar, Mucuripe', fr: 'Avenue Beira Mar, Mucuripe' },
    openingHours: { en: 'Open 24h', pt: 'Aberto 24h', es: 'Abierto 24h', fr: 'Ouvert 24h' },
    rating: 4.7,
    category: 'Beaches',
    imageUrl: 'https://visit-fortaleza.com/wp-content/uploads/Praia-do-Mucuripe_4_-Foto-Joao-Crisosthomo.jpg',
    coords: { lat: -3.7272, lng: -38.4862 },
    nearbyRestaurantIds: ['coco-bambu-beiramar']
  },
  {
    id: 'futuro',
    title: { en: 'Future Beach', pt: 'Praia do Futuro', es: 'Playa del Futuro', fr: 'Plage du Futur' },
    description: { en: 'Best infrastructure for swimming, with famous mega-barracas.', pt: 'Melhor infraestrutura para banho, com as famosas mega-barracas.', es: 'Mejor infraestructura para el baño, con las famosas mega-barracas.', fr: 'Meilleure infrastructure pour la baignade, avec les célèbres méga-barracas.' },
    address: { en: 'Clóvis Arrais Maia Avenue', pt: 'Av. Clóvis Arrais Maia', es: 'Avenida Clóvis Arrais Maia', fr: 'Avenue Clóvis Arrais Maia' },
    openingHours: { en: 'Open 24h', pt: 'Aberto 24h', es: 'Abierto 24h', fr: 'Ouvert 24h' },
    rating: 4.8,
    category: 'Beaches',
    imageUrl: 'https://cdn.shortpixel.ai/spai/q_glossy+ret_img+to_webp/viajandocomamalarosa.com.br/wp-content/uploads/2021/07/whatsapp-image-2021-07-05-at-130852-1-1280x650.jpeg',
    coords: { lat: -3.7383, lng: -38.4552 },
    nearbyRestaurantIds: []
  },
  {
    id: 'sabiaguaba',
    title: { en: 'Sabiaguaba Beach', pt: 'Praia da Sabiaguaba', es: 'Playa de Sabiaguaba', fr: 'Plage de Sabiaguaba' },
    description: { en: 'A wild, preserved beach where the river meets the sea.', pt: 'Uma praia selvagem e preservada onde o rio encontra o mar.', es: 'Una playa salvaje y preservada donde el río se une al mar.', fr: 'Une plage sauvage et préservée où le fleuve rencontre la mer.' },
    address: { en: 'Sabiaguaba, Fortaleza', pt: 'Sabiaguaba, Fortaleza', es: 'Sabiaguaba, Fortaleza', fr: 'Sabiaguaba, Fortaleza' },
    openingHours: { en: 'Open 24h', pt: 'Aberto 24h', es: 'Abierto 24h', fr: 'Ouvert 24h' },
    rating: 4.6,
    category: 'Beaches',
    imageUrl: 'https://blog.rotacombo.com/wp-content/uploads/2026/01/praia-de-sabiaguaba.webp',
    coords: { lat: -3.7782, lng: -38.4412 },
    nearbyRestaurantIds: []
  },
  {
    id: 'abreulandia',
    title: { en: 'Abreulândia Beach', pt: 'Praia da Abreulândia', es: 'Playa de Abreulândia', fr: 'Plage d\'Abreulândia' },
    description: { en: 'Quiet beach area in Fortaleza.', pt: 'Área de praia tranquila em Fortaleza.', es: 'Zona de playa tranquila en Fortaleza.', fr: 'Plage tranquille à Fortaleza.' },
    address: { en: 'Abreulândia, Fortaleza', pt: 'Abreulândia, Fortaleza', es: 'Abreulândia, Fortaleza', fr: 'Abreulândia, Fortaleza' },
    openingHours: { en: 'Open 24h', pt: 'Aberto 24h', es: 'Abierto 24h', fr: 'Ouvert 24h' },
    rating: 4.5,
    category: 'Beaches',
    imageUrl: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0b/64/3c/3b/praia.jpg?w=900&h=500&s=1',
    coords: { lat: -3.8182, lng: -38.4212 },
    nearbyRestaurantIds: []
  },
  {
    id: 'theatro-ja',
    title: { en: 'José de Alencar Theater', pt: 'Theatro José de Alencar', es: 'Teatro José de Alencar', fr: 'Théâtre José de Alencar' },
    description: { en: 'Art Nouveau landmark and architectural treasure.', pt: 'Marco do Art Nouveau e tesouro arquitetônico de Fortaleza.', es: 'Hito del Art Nouveau y tesoro arquitectónico.', fr: 'Monument Art nouveau et trésor architectural.' },
    address: { en: '696 Liberato Barroso Street', pt: 'Rua Liberato Barroso, 696', es: 'Calle Liberato Barroso, 696', fr: 'Rue Liberato Barroso, 696' },
    openingHours: { en: '09:00 AM - 05:00 PM', pt: '09:00 - 17:00', es: '09:00 - 17:00', fr: '09h00 - 17h00' },
    rating: 4.9,
    category: 'Culture',
    imageUrl: 'https://theatrojosedealencar.cultura.ce.gov.br/wp-content/uploads/2023/11/tja-foto_Easy-Resize.com_.jpg',
    coords: { lat: -3.7288, lng: -38.5305 },
    nearbyRestaurantIds: []
  },
  {
    id: 'belchior',
    title: { en: 'Belchior Cultural Center', pt: 'Centro Cultural Belchior', es: 'Centro Cultural Belchior', fr: 'Centre Culturel Belchior' },
    description: { en: 'Dedicated to Ceará\'s artistic heritage.', pt: 'Dedicado ao patrimônio artístico do Ceará.', es: 'Dedicado al patrimonio artístico de Ceará.', fr: 'Dédié au patrimoine artistique du Ceará.' },
    address: { en: '440 Pacatuba Street', pt: 'Rua dos Pacatuba, 440', es: 'Calle Pacatuba, 440', fr: 'Rue Pacatuba, 440' },
    openingHours: { en: '10:00 AM - 09:00 PM', pt: '10:00 - 21:00', es: '10:00 - 21:00', fr: '10h00 - 21h00' },
    rating: 4.7,
    category: 'Culture',
    imageUrl: 'https://cultura.fortaleza.ce.gov.br/images/Equipamentos/ccbel_equip.png',
    coords: { lat: -3.7215, lng: -38.5155 },
    nearbyRestaurantIds: []
  },
  {
    id: 'estoril',
    title: { en: 'Estoril', pt: 'Estoril', es: 'Estoril', fr: 'Estoril' },
    description: { en: 'Historic building at Iracema Beach.', pt: 'Edifício histórico na Praia de Iracema.', es: 'Edificio histórico en la playa de Iracema.', fr: 'Bâtiment historique sur la plage d\'Iracema.' },
    address: { en: '397 Tabajaras Street', pt: 'Rua dos Tabajaras, 397', es: 'Calle Tabajaras, 397', fr: 'Rue Tabajaras, 397' },
    openingHours: { en: '09:00 AM - 06:00 PM', pt: '09:00 - 18:00', es: '09:00 - 18:00', fr: '09h00 - 18h00' },
    rating: 4.6,
    category: 'Culture',
    imageUrl: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/05/bc/a8/91/estoril.jpg?w=1200&h=-1&s=1',
    coords: { lat: -3.7212, lng: -38.5185 },
    nearbyRestaurantIds: []
  },
  {
    id: 'museu-foto',
    title: { en: 'Photography Museum', pt: 'Museu da Fotografia', es: 'Museu de la Fotografía', fr: 'Musée de la Photographie' },
    description: { en: 'One of Brazil\'s most important collections of photography.', pt: 'Uma das mais importantes coleções de fotografia do Brasil.', es: 'Una de las colecciones de fotografía más importantes.', fr: 'L\'une des plus importantes collections de photos.' },
    address: { en: '545 Frederico Borges Street', pt: 'Rua Frederico Borges, 545', es: 'Calle Frederico Borges, 545', fr: 'Rue Frederico Borges, 545' },
    openingHours: { en: '12:00 PM - 08:00 PM', pt: '12:00 - 20:00', es: '12:00 - 20:00', fr: '12h00 - 20h00' },
    rating: 4.9,
    category: 'Culture',
    imageUrl: 'https://www.opovo.com.br/_midias/jpg/2022/03/28/museu_da_fotografia_celso_oliveira-18413536.jpg?20220330070123',
    coords: { lat: -3.7312, lng: -38.4882 },
    nearbyRestaurantIds: ['moleskine']
  },
  {
    id: 'museu-ceara',
    title: { en: 'Ceará Museum', pt: 'Museu do Ceará', es: 'Museu de Ceará', fr: 'Musée du Ceará' },
    description: { en: 'Historic palace showcasing state history.', pt: 'Palácio histórico que mostra a história do estado.', es: 'Palacio histórico que muestra la historia del estado.', fr: 'Palais historique retraçant l\'histoire de l\'État.' },
    address: { en: 'Senador Alencar Street, 348', pt: 'Rua Sen. Alencar, 348', es: 'Calle Sen. Alencar, 348', fr: 'Rue Sen. Alencar, 348' },
    openingHours: { en: '09:00 AM - 05:00 PM', pt: '09:00 - 17:00', es: '09:00 - 17:00', fr: '09h00 - 17h00' },
    rating: 4.7,
    category: 'Culture',
    imageUrl: 'https://www.opovo.com.br/_midias/jpg/2022/02/01/museu_do_ceara__2_-18009350.jpg',
    coords: { lat: -3.7262, lng: -38.5262 },
    nearbyRestaurantIds: []
  },
  {
    id: 'mis-ce',
    title: { en: 'Image and Sound Museum', pt: 'Museu da Imagem e do Som', es: 'Museo de Imagen y Sonido', fr: 'Musée de l\'Image et du Son' },
    description: { en: 'Cultural space for digital art.', pt: 'Espaço cultural para arte digital.', es: 'Espacio cultural para el arte digital.', fr: 'Espace cultural dédié à l\'art numérique.' },
    address: { en: '441 Barão de Studart Avenue', pt: 'Av. Barão de Studart, 441', es: 'Avenida Barão de Studart, 441', fr: 'Avenue Barão de Studart, 441' },
    openingHours: { en: '10:00 AM - 08:00 PM', pt: '10:00 - 20:00', es: '10:00 - 20:00', fr: '10h00 - 20h00' },
    rating: 4.8,
    category: 'Culture',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/9/9e/MIS-CE_-_Casa_de_Fausto_Cabral_15.jpg',
    coords: { lat: -3.7342, lng: -38.5022 },
    nearbyRestaurantIds: []
  },
  {
    id: 'passeio-publico',
    title: { en: 'Passeio Público', pt: 'Passeio Público', es: 'Passeio Público', fr: 'Passeio Público' },
    description: { en: 'Fortaleza\'s oldest square.', pt: 'A praça mais antiga de Fortaleza.', es: 'La plaza más antigua de Fortaleza.', fr: 'La plus ancienne place de Fortaleza.' },
    address: { en: 'Alberto Nepomuceno Avenue', pt: 'Av. Alberto Nepomuceno', es: 'Avenida Alberto Nepomuceno', fr: 'Avenue Alberto Nepomuceno' },
    openingHours: { en: '06:00 AM - 08:00 PM', pt: '06:00 - 20:00', es: '06:00 - 20:00', fr: '06h00 - 20h00' },
    rating: 4.6,
    category: 'Historical Places',
    imageUrl: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0c/a3/df/4c/lagos-encantadores.jpg?w=900&h=500&s=1',
    coords: { lat: -3.7222, lng: -38.5262 },
    nearbyRestaurantIds: []
  },
  {
    id: 'iracema-guardia',
    title: { en: 'Guardian Iracema Statue', pt: 'Iracema Guardiã', es: 'Iracema Guardiana', fr: 'Iracema Gardienne' },
    description: { en: 'Iconic monument of Fortaleza.', pt: 'Monumento icônico de Fortaleza.', es: 'Monumento icónico de Fortaleza.', fr: 'Monument emblématique de Fortaleza.' },
    address: { en: 'Aterro de Iracema', pt: 'Aterro da Praia de Iracema', es: 'Aterro de Iracema', fr: 'Aterro d\'Iracema' },
    openingHours: { en: 'Open 24h', pt: 'Aberto 24h', es: 'Abierto 24h', fr: 'Ouvert 24h' },
    rating: 4.8,
    category: 'Historical Places',
    imageUrl: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/12/ca/e8/c2/lindacultura-e-tradicao.jpg?w=1200&h=-1&s=1',
    coords: { lat: -3.7202, lng: -38.5132 },
    nearbyRestaurantIds: []
  },
  {
    id: 'praca-leoes',
    title: { en: 'Lions Square', pt: 'Praça dos Leões', es: 'Plaza de los Leones', fr: 'Place des Lions' },
    description: { en: 'Historic square in Fortaleza.', pt: 'Praça histórica em Fortaleza.', es: 'Plaza histórica en Fortaleza.', fr: 'Place historique à Fortaleza.' },
    address: { en: 'Rua General Bezerril', pt: 'Rua General Bezerril', es: 'Rua General Bezerril', fr: 'Rua General Bezerril' },
    openingHours: { en: 'Open 24h', pt: 'Aberto 24h', es: 'Abierto 24h', fr: 'Ouvert 24h' },
    rating: 4.5,
    category: 'Historical Places',
    imageUrl: 'https://mapacultural.secult.ce.gov.br/files/space/293/IMG_2485.jpg',
    coords: { lat: -3.7252, lng: -38.5262 },
    nearbyRestaurantIds: []
  },
  {
    id: 'igreja-rosario',
    title: { en: 'Rosary Church', pt: 'Igreja do Rosário', es: 'Iglesia del Rosario', fr: 'Église du Rosaire' },
    description: { en: 'Oldest church in Fortaleza.', pt: 'Igreja mais antiga de Fortaleza.', es: 'Iglesia más antiga de Fortaleza.', fr: 'Plus ancienne église de Fortaleza.' },
    address: { en: 'Major Facundo Street', pt: 'Rua Major Facundo', es: 'Calle Major Facundo', fr: 'Rue Major Facundo' },
    openingHours: { en: '08:00 AM - 05:00 PM', pt: '08:00 - 17:00', es: '08:00 - 17:00', fr: '08h00 - 17h00' },
    rating: 4.7,
    category: 'Historical Places',
    imageUrl: 'https://www.opovo.com.br/_midias/jpg/2023/08/03/818x460/1__estrutura_da_igreja_do_rosario__1-22867783.jpg',
    coords: { lat: -3.7242, lng: -38.5262 },
    nearbyRestaurantIds: []
  },
  {
    id: 'joao-felipe',
    title: { en: 'João Felipe Station', pt: 'Estação João Felipe', es: 'Estación João Felipe', fr: 'Gare João Felipe' },
    description: { en: 'Former main railway station.', pt: 'Antiga estação ferroviária principal.', es: 'Antiga estação de tren.', fr: 'Ancienne gare principale.' },
    address: { en: 'Castro e Silva Street', pt: 'Rua Castro e Silva', es: 'Calle Castro e Silva', fr: 'Rue Castro e Silva' },
    openingHours: { en: 'External viewing', pt: 'Visitação externa', es: 'Vista externa', fr: 'Vue externe' },
    rating: 4.4,
    category: 'Historical Places',
    imageUrl: 'https://arteforadomuseu.com.br/site/wp-content/uploads/2019/10/Esta%C3%A7%C3%A3o-Jo%C3%A3o-Felipe.jpg',
    coords: { lat: -3.7222, lng: -38.5292 },
    nearbyRestaurantIds: []
  },
  {
    id: 'farol-mucuripe',
    title: { en: 'Mucuripe Lighthouse', pt: 'Farol do Mucuripe', es: 'Faro de Mucuripe', fr: 'Phare de Mucuripe' },
    description: { en: 'Historic lighthouse in Fortaleza.', pt: 'Farol histórico em Fortaleza.', es: 'Faro histórico.', fr: 'Phare historique.' },
    address: { en: 'Mucuripe, Fortaleza', pt: 'Mucuripe, Fortaleza', es: 'Mucuripe, Fortaleza', fr: 'Mucuripe, Fortaleza' },
    openingHours: { en: 'External viewing', pt: 'Visitação externa', es: 'Vista externa', fr: 'Vue externe' },
    rating: 4.3,
    category: 'Historical Places',
    imageUrl: 'https://diariodonordeste.verdesmares.com.br/image/contentid/policy:1.3744339:1771593180/Farol%20do%20Mucuripe%201%20-%20Cr%C3%A9dito%20Ismael%20Soares.webp',
    coords: { lat: -3.7212, lng: -38.4792 },
    nearbyRestaurantIds: []
  },
  {
    id: 'rio-branco',
    title: { en: 'Rio Branco Park', pt: 'Parque Rio Branco', es: 'Parque Rio Branco', fr: 'Parc Rio Branco' },
    description: { en: 'Leisure and green area.', pt: 'Área verde e de lazer.', es: 'Zona verde y de ocio.', fr: 'Espace vert et de loisirs.' },
    address: { en: 'Joaquim Távora, Fortaleza', pt: 'Joaquim Távora, Fortaleza', es: 'Joaquim Távora, Fortaleza', fr: 'Joaquim Távora, Fortaleza' },
    openingHours: { en: '06:00 AM - 10:00 PM', pt: '06:00 - 22:00', es: '06:00 - 22:00', fr: '06h00 - 22h00' },
    rating: 4.5,
    category: 'Parks',
    imageUrl: 'https://www.opovo.com.br/_midias/jpg/2024/08/15/parque_rio_branco_credito_prefeitura_de_fortaleza-29667351.jpg',
    coords: { lat: -3.7482, lng: -38.5132 },
    nearbyRestaurantIds: []
  },
  {
    id: 'rachel-queiroz',
    title: { en: 'Rachel de Queiroz Park', pt: 'Parque Rachel de Queiroz', es: 'Parque Rachel de Queiroz', fr: 'Parc Rachel de Queiroz' },
    description: { en: 'Linear park with lakes and trails.', pt: 'Parque linear com lagos e trilhas.', es: 'Parque lineal con lagos y senderos.', fr: 'Parc linéaire avec lacs et sentiers.' },
    address: { en: 'Presidente Kennedy, Fortaleza', pt: 'Presidente Kennedy, Fortaleza', es: 'Presidente Kennedy, Fortaleza', fr: 'Presidente Kennedy, Fortaleza' },
    openingHours: { en: 'Open 24h', pt: 'Aberto 24h', es: 'Abierto 24h', fr: 'Ouvert 24h' },
    rating: 4.8,
    category: 'Parks',
    imageUrl: 'https://visit-fortaleza.com/wp-content/uploads/DJI_0734.jpg',
    coords: { lat: -3.7282, lng: -38.5532 },
    nearbyRestaurantIds: []
  },
  {
    id: 'jardim-japones',
    title: { en: 'Japanese Garden', pt: 'Jardim Japonês', es: 'Jardín Japonés', fr: 'Jardin Japonais' },
    description: { en: 'Zen space with ocean view.', pt: 'Espaço Zen com vista para o mar.', es: 'Espaço Zen con vistas al mar.', fr: 'Espace Zen avec vue sur la mer.' },
    address: { en: 'Beira Mar Avenue, Meireles', pt: 'Av. Beira Mar, Meireles', es: 'Avenida Beira Mar, Meireles', fr: 'Avenue Beira Mar, Meireles' },
    openingHours: { en: '08:00 AM - 10:00 PM', pt: '08:00 - 22:00', es: '08:00 - 22:00', fr: '08h00 - 22h00' },
    rating: 4.7,
    category: 'Parks',
    imageUrl: 'https://dicasdefortalezaejeri.com.br/wp-content/uploads/sites/29/2023/07/fortaleza-jaridm-japones-avenida.jpg',
    coords: { lat: -3.7272, lng: -38.4882 },
    nearbyRestaurantIds: ['coco-bambu-beiramar']
  },
  {
    id: 'adahil-barreto',
    title: { en: 'Adahil Barreto Park', pt: 'Parque Adahil Barreto', es: 'Parque Adahil Barreto', fr: 'Parc Adahil Barreto' },
    description: { en: 'Nature reserve part of Cocó Park.', pt: 'Reserva natural parte do Parque do Cocó.', es: 'Reserva natural parte de Cocó.', fr: 'Réserve naturelle partie du Parc du Cocó.' },
    address: { en: 'Dionísio Torres, Fortaleza', pt: 'Dionísio Torres, Fortaleza', es: 'Dionísio Torres, Fortaleza', fr: 'Dionísio Torres, Fortaleza' },
    openingHours: { en: '06:00 AM - 08:00 PM', pt: '06:00 - 20:00', es: '06:00 - 20:00', fr: '06h00 - 20h00' },
    rating: 4.6,
    category: 'Parks',
    imageUrl: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/19/d9/60/4b/parquinho.jpg?w=900&h=500&s=1',
    coords: { lat: -3.7512, lng: -38.4982 },
    nearbyRestaurantIds: []
  },
  {
    id: 'coco',
    title: { en: 'Cocó Park', pt: 'Parque do Cocó', es: 'Parque de Cocó', fr: 'Parc du Cocó' },
    description: { en: 'Large ecological park protecting mangroves.', pt: 'Grande parque ecológico que protege o manguezal.', es: 'Gran parque ecológico.', fr: 'Grand parc écologique.' },
    address: { en: 'Padre Antônio Tomás Avenue', pt: 'Av. Padre Antônio Tomás', es: 'Avenida Padre Antônio Tomás', fr: 'Avenue Padre Antônio Tomás' },
    openingHours: { en: '05:30 AM - 10:00 PM', pt: '05:30 - 22:00', es: '05:30 - 22:00', fr: '05h30 - 22h00' },
    rating: 4.7,
    category: 'Parks',
    imageUrl: 'https://www.ce.gov.br/wp-content/uploads/2024/08/Parque-do-Coco1-1.jpg',
    coords: { lat: -3.7468, lng: -38.4835 },
    nearbyRestaurantIds: []
  }
];
