
import type {NextConfig} from 'next';

const nextConfig: NextConfig = {
  /* config options here */
  typescript: {
    ignoreBuildErrors: true,
  },
  eslint: {
    ignoreDuringBuilds: true,
  },
  images: {
    remotePatterns: [
      { protocol: 'https', hostname: 'placehold.co' },
      { protocol: 'https', hostname: 'images.unsplash.com' },
      { protocol: 'https', hostname: 'picsum.photos' },
      { protocol: 'https', hostname: 'upload.wikimedia.org' },
      { protocol: 'https', hostname: 'dicasdefortalezaejeri.com.br' },
      { protocol: 'https', hostname: 'cdn.shortpixel.ai' },
      { protocol: 'https', hostname: 'dynamic-media-cdn.tripadvisor.com' },
      { protocol: 'https', hostname: 'media-cdn.tripadvisor.com' },
      { protocol: 'https', hostname: '3coracoes.com.br' },
      { protocol: 'https', hostname: 'cms-blog.saipos.com' },
      { protocol: 'https', hostname: 't4.ftcdn.net' },
      { protocol: 'https', hostname: 'semeia.org.br' },
      { protocol: 'https', hostname: 'comshalom.org' },
      { protocol: 'https', hostname: 'ipatrimonio.org' },
      { protocol: 'https', hostname: 'cf.bstatic.com' },
      { protocol: 'https', hostname: 'pacotestravel.com.br' },
      { protocol: 'https', hostname: 'i.pinimg.com' },
      { protocol: 'https', hostname: 'i.ibb.co' },
      { protocol: 'https', hostname: 'img2.oastatic.com' },
      { protocol: 'https', hostname: 'visit-fortaleza.com' },
      { protocol: 'https', hostname: 'blog.rotacombo.com' },
      { protocol: 'https', hostname: 'villaaquiraz.com.br' },
      { protocol: 'https', hostname: 'theatrojosedealencar.cultura.ce.gov.br' },
      { protocol: 'https', hostname: 'cultura.fortaleza.ce.gov.br' },
      { protocol: 'https', hostname: 'arteforadomuseu.com.br' },
      { protocol: 'https', hostname: 'diariodonordeste.verdesmares.com.br' },
      { protocol: 'https', hostname: 'galeriadaarquitetura.com.br' },
      { protocol: 'https', hostname: 'ce.gov.br' },
      { protocol: 'https', hostname: 'www.ce.gov.br' },
      { protocol: 'https', hostname: 'cocobambu.com.br' },
      { protocol: 'https', hostname: 'primeiramesa.com.br' },
      { protocol: 'https', hostname: 'cabanadelprimo.com.br' },
      { protocol: 'https', hostname: 'grupogeppos.com.br' },
      { protocol: 'https', hostname: 'viagemeturismo.abril.com.br' },
      { protocol: 'https', hostname: 'cantinhodofrangooficial.com.br' },
      { protocol: 'https', hostname: 'casabalcone.com.br' },
      { protocol: 'https', hostname: 'seara-praia-hotel.hoteis-noreste-de-brasil.com' },
      { protocol: 'https', hostname: 'magnapraiahotel.com.br' },
      { protocol: 'https', hostname: 'd2h50f2ee3zau3.cloudfront.net' },
      { protocol: 'https', hostname: 'mapacultural.secult.ce.gov.br' },
      { protocol: 'https', hostname: 'opovo.com.br' },
      { protocol: 'https', hostname: 'www.opovo.com.br' },
      { protocol: 'https', hostname: 'lirp.cdn-website.com' },
      { protocol: 'https', hostname: 'media.staticontent.com' },
      { protocol: 'https', hostname: 'ahstatic.com' },
      { protocol: 'https', hostname: 'cdn-icons-png.flaticon.com' },
      { protocol: 'https', hostname: 'i.imgur.com' },
    ],
  },
};

export default nextConfig;
