
import type {NextConfig} from 'next';

const nextConfig: NextConfig = {
  /* config options here */
  typescript: {
    ignoreBuildErrors: true,
  },
  eslint: {
    ignoreDuringBuilds: true,
  },
  images: {
    remotePatterns: [
      { protocol: 'https', hostname: '**.placehold.co' },
      { protocol: 'https', hostname: '**.images.unsplash.com' },
      { protocol: 'https', hostname: '**.picsum.photos' },
      { protocol: 'https', hostname: '**.wikimedia.org' },
      { protocol: 'https', hostname: '**.dicasdefortalezaejeri.com.br' },
      { protocol: 'https', hostname: '**.shortpixel.ai' },
      { protocol: 'https', hostname: '**.tripadvisor.com' },
      { protocol: 'https', hostname: '**.3coracoes.com.br' },
      { protocol: 'https', hostname: '**.saipos.com' },
      { protocol: 'https', hostname: '**.ftcdn.net' },
      { protocol: 'https', hostname: '**.semeia.org.br' },
      { protocol: 'https', hostname: '**.comshalom.org' },
      { protocol: 'https', hostname: '**.ipatrimonio.org' },
      { protocol: 'https', hostname: 'cf.bstatic.com' },
      { protocol: 'https', hostname: '**.cf.bstatic.com' },
      { protocol: 'https', hostname: '**.pacotestravel.com.br' },
      { protocol: 'https', hostname: '**.pinimg.com' },
      { protocol: 'https', hostname: 'i.ibb.co' },
      { protocol: 'https', hostname: '**.ibb.co' },
      { protocol: 'https', hostname: '**.visit-fortaleza.com' },
      { protocol: 'https', hostname: '**.rotacombo.com' },
      { protocol: 'https', hostname: '**.villaaquiraz.com.br' },
      { protocol: 'https', hostname: 'ce.gov.br' },
      { protocol: 'https', hostname: '**.ce.gov.br' },
      { protocol: 'https', hostname: '**.arteforadomuseu.com.br' },
      { protocol: 'https', hostname: '**.verdesmares.com.br' },
      { protocol: 'https', hostname: '**.galeriadaarquitetura.com.br' },
      { protocol: 'https', hostname: 'galeriadaarquitetura.com.br' },
      { protocol: 'https', hostname: 'cocobambu.com.br' },
      { protocol: 'https', hostname: '**.cocobambu.com.br' },
      { protocol: 'https', hostname: '**.primeiramesa.com.br' },
      { protocol: 'https', hostname: 'cabanadelprimo.com.br' },
      { protocol: 'https', hostname: '**.cabanadelprimo.com.br' },
      { protocol: 'https', hostname: '**.grupogeppos.com.br' },
      { protocol: 'https', hostname: '**.abril.com.br' },
      { protocol: 'https', hostname: 'cantinhodofrangooficial.com.br' },
      { protocol: 'https', hostname: '**.cantinhodofrangooficial.com.br' },
      { protocol: 'https', hostname: 'casabalcone.com.br' },
      { protocol: 'https', hostname: '**.casabalcone.com.br' },
      { protocol: 'https', hostname: '**.hoteis-noreste-de-brasil.com' },
      { protocol: 'https', hostname: 'magnapraiahotel.com.br' },
      { protocol: 'https', hostname: '**.magnapraiahotel.com.br' },
      { protocol: 'https', hostname: '**.cloudfront.net' },
      { protocol: 'https', hostname: 'opovo.com.br' },
      { protocol: 'https', hostname: '**.opovo.com.br' },
      { protocol: 'https', hostname: '**.cdn-website.com' },
      { protocol: 'https', hostname: '**.staticontent.com' },
      { protocol: 'https', hostname: '**.ahstatic.com' },
      { protocol: 'https', hostname: 'i.imgur.com' },
      { protocol: 'https', hostname: '**.flaticon.com' },
    ],
  },
};

export default nextConfig;
